### PR TITLE
feat: support directives

### LINKED ISSUE #155: Option to import directives in UI resolver?
Related to #152, I'm working on adding a few missing items to the PrimeVue resolver and I would love the ability to add a few directives that it uses.    I like that it can already import the CSS, it'd be great to have it handle the remaining directives for PrimeVue.

I can do a PR for the easier part of updating the resolver, but I'm not sure whether you even want any ability to add directives and if so, how to do that :)

```js
app.directive('tooltip', Tooltip)
app.directive('badge', BadgeDirective)
app.directive('ripple', Ripple)
```

### PR DESCRIPTION
**Pull request by sxzz**
close #155

### CODE REVIEW

**Comment by sxzz** [comment]
Yes. But in Vue 2, it will be very hard to transform without AST.
```js
var render = function () {
  var _vm = this
  var _h = _vm.$createElement
  var _c = _vm._self._c || _h
  return _c("test-comp", {
    directives: [
      { name: "loading", rawName: "v-loading", value: 123, expression: "123" }
    ]
  })
}
```

**Comment by antfu** [comment]
But honestly, do we really need this? I found directives are rarely used for me. For the few of them, I think it's better to register globally - I don't expect directives to be huge that impacting the code-splitting.

**Comment by antfu** [comment]
I am fine to have this but I don't want to introduce Babel that affecting the existing users just because of a relatively rarely used feature. If you absolutely need this, I think we should keep the original transformation, and have babel enabled only for Vue 2 directives with an explicit flag to enable (default to false).

**Comment by sxzz** [comment]
OK. I will change it.

**Comment by sxzz** [comment]
Hi, when can it gets merged?

**Pull request merged**
