### PR TITLE
feat: add dts transformer

### PR DESCRIPTION
**Pull request by dalirnet**
### Description

An option was added for transforming declaration lines before writing them to the final dts file.

### Linked Issues
[#460](https://github.com/antfu/unplugin-vue-components/issues/460)

### Additional context

This option allows me to exclude Ant Design icon components from the dts file without excluding them from the component resolver, to speed up VScode autocomplete.

### CODE REVIEW

**Comment by dalirnet** [comment]
Dear @antfu
First of all, happy birthday! Next, please review the my PR.

**Comment by antfu** [comment]
I feel this API is designed a bit too specific to solve your need. I don't see it will be used by other users as it would require them to rewrite the function to filter with the knowledge of the object format.

The other approach I can think about is in the resolved object, the resolver could provide an additional `dts: false` to be filtered on the dts generation.

**Comment by dalirnet** [comment]
It is possible that this problem will occur for all users of AntD,  can you suggest a better solution? 🙏

**Comment by antfu** [comment]
As I said, we could have a `dts` option in the returned object of resolver, 

https://github.com/antfu/unplugin-vue-components/blob/86d34956d7ee4ea58f2a7f6d86fb5836bea30c70/src/core/resolvers/element-ui.ts#L52-L60

While making it configurable via antd's options

**Pull request closed without merging**
