### PR TITLE
fix: directive for vue 2.7

### PR DESCRIPTION
**Pull request by sxzz**
### Description

In Vue 2.7, `render` is renamed to `_sfc_render`.

### CODE REVIEW

**Comment by cczw2010** [comment]
[unplugin-vue-components:directive] Cannot find render function position. 

which is always in this fix version. 

I'll back version until 0.22.3 is not thore the error.

**Comment by sxzz** [comment]
`rollup-plugin-vue` is deprecated. Try `unplugin-vue` or `@vitejs/plugin-vue`

**Comment by cczw2010** [comment]
> 

ok, but my project is base rollup & vue2

**Comment by sxzz** [comment]
@cczw2010 Try this demo https://github.com/sxzz/vue2-directive-demo

**Comment by cczw2010** [comment]
> @cczw2010 Try this demo https://github.com/sxzz/vue2-directive-demo

I'll try.  And if possiable ,hope to add this small modification in the next version.

**Comment by sxzz** [comment]
PR welcome

**Comment by sconix** [comment]
We are still getting the error of [unplugin-vue-components:directive] Cannot find render function position.

**Comment by sxzz** [comment]
Could you please open an issue and provide a reproduction?


https://antfu.me/posts/why-reproductions-are-required

**Pull request merged**
