### PR TITLE
feat(bootstrap-vue-plus): new resolver.

### PR DESCRIPTION
**Pull request by kw214**
[bootstrap-vue-plus](https://github.com/bootstrap-vue-plus/bootstrap-vue-plus)

### CODE REVIEW

**Comment by see** [comment]
@sxzz  I have now started a new project, the name is `bootstrap-vue-plus`, the architecture and development of the repo is based on `element-plus`, and I plan to upgrade `bootstrap-vue` to adapt to vue 3. The third parties involved are declared in the `license`

**Comment by jd-solanki** [comment]
You link https://bootstrap-vue-plus.com/ isn't working

**Comment by see** [comment]
@jd-solanki please visit [bootstrap vue plus](https://github.com/bootstrap-vue-plus/bootstrap-vue-plus)

**Comment by jd-solanki** [comment]
> @jd-solanki please visit [bootstrap vue plus](https://github.com/bootstrap-vue-plus/bootstrap-vue-plus)

I was referring to you website URL: https://bootstrap-vue-plus.com/

**Comment by see** [comment]
website is under development

**Comment by antfu** [comment]
Thanks for your contributions. We are sorry we no longer accept new resolvers:
https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/_READ_BEFORE_CONTRIBUTE.md

**Pull request closed without merging**
