### PR TITLE
feat(resolvers): add bootstrap-vue-next resolver

### PR DESCRIPTION
**Pull request by VividLemon**
### Description

Adds bootstrap-vue-next resolver and adds deprecation note about BootstrapVue3

### Additional context

BootstrapVue3 has been merged as an official repo in BootstrapVue, and is renamed to BootstrapVueNext https://www.npmjs.com/package/bootstrap-vue-next

### CODE REVIEW

**Comment by VividLemon** [comment]
@antfu

**Comment by makroxyz** [comment]
Can you merge please?

**Comment by boindil** [comment]
@antfu please merge!

**Comment by xaviersand** [comment]
is there a way to use this code using npm ? i would like to start migrating a projet from vue2 to 3 and i use bootstrap vue.
Otherwise can you give a date on when you will merge the fix ? (i'm litteraly coming here every day for about 2 weeks to see if it's done)

**Pull request merged**
