### PR TITLE
feat: add view-ui-plus resolver

### PR DESCRIPTION
**Pull request by likuner**

### CODE REVIEW

**Comment by antfu** [comment]
I would wait until view-ui-plus get more adoption

**Comment by see** [comment]
> I would wait until view-ui-plus get more adoption

Which project is not built from scratch. The great thing about GitHub is that it doesn't restrict unpopular projects.

**Comment by sxzz** [comment]
@see IMHO, `view-ui-plus` can provide this resolver by itself. There are too many issues in this repo about resolvers instead of the plugin self.

TBH, maybe Element Plus will built-in itself's resolver in the future, then we can upgrade or maintain it better.

**Comment by see** [comment]
@sxzz `unplugin-element-plus`?

**Comment by sxzz** [comment]
@see No, this plugin is used on importing style only automatically, instead of importing Vue componments.

**Comment by see** [comment]
@sxzz another separate library?

**Comment by sxzz** [comment]
@see I mean **maybe** Element Plus will do it **in the future**. Currently haven't.

**Comment by superlbr** [comment]
pending too long as view-ui forgotten

**Comment by antfu** [comment]
Thanks for your contributions. We are sorry we no longer accept new resolvers:
https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/_READ_BEFORE_CONTRIBUTE.md

**Pull request closed without merging**
