### PR TITLE
fix(element-plus): get esm package version, closes #194

### LINKED ISSUE #194: ESM throw a Error 'Dynamic require of "element-plus/package.json" is not supported'
in utils.ts function `getPkgVersion` use `require` to load 'package.json', but mjs file not have `require`

### PR DESCRIPTION
**Pull request by nabaonan**
fix issue 194  use resolve instead commonjs require() to read package.json version

### CODE REVIEW

**Comment by sxzz** [comment]
How about using https://www.npmjs.com/package/local-pkg to get version?

**Comment by antfu** [comment]
https://github.com/antfu/unplugin-vue-components/blob/bb6dbeb3cf8fbf2bc705517159d7c9249880a712/src/core/transforms/directive/vue2.ts#L6

**Comment by nabaonan** [comment]
> How about using https://www.npmjs.com/package/local-pkg to get version?
it is great idea!!

**Comment by nabaonan** [comment]
the resolver's return type is promise, and  not pass the tests, is the resolver type must not be a promise?

**Comment by sxzz** [comment]
@antfu Maybe we can add a sync version to `local-pkg`

**Comment by nabaonan** [comment]
> sync

but getPkgVersion method must be a sync method, i didn't found a good method to resolve it , do you have any other good idea to make async method to sync.

**Comment by antfu** [comment]
You can just make `getPkgVersion` async and move the usage inside `resolve` which supports awats.

**Comment by antfu** [comment]
```ts
export function ElementPlusResolver(
  options: ElementPlusResolverOptions = {},
): ComponentResolver[] {
  let optionsResolved: ElementPlusResolverOptionsResolved | undefined

  async function resolveOptions() {
    if (optionsResolved)
      return optionsResolved
    optionsResolved = {
      ssr: false,
      version: await getPkgVersion('element-plus', '1.1.0-beta.21'),
      importStyle: 'css',
      directives: true,
      ...options,
    }
    return optionsResolved
  }

  return [
    {
      type: 'component',
      resolve: async(name: string) => {
        return resolveComponent(name, await resolveOptions())
      },
    },
    {
      type: 'directive',
      resolve: async(name: string) => {
        return resolveDirective(name, await resolveOptions())
      },
    },
  ]
}
```

**Pull request merged**
